### ISSUE TITLE
When can I have a Chinese version?

### ISSUE THREAD

**Issue by xiesi88** [semontesdeoca/MNPR#1] opened 2018-06-14 05:27 UTC
I did not install it successfully in the Chinese version of Maya 2017. When can I have a Chinese version?

# 错误: file: G:/Software/MNPR/install.mel line 27: ValueError: file G:/Software/MNPR/scripts/coopLib.py line 64: could not convert string to float: zh_CN #

**Comment by semontesdeoca** [comment] 2018-06-14 06:00
We unfortunately don't understand Chinese and do not have a Chinese version of Maya laying around to thoroughly test things out. Hopefully now that's open source, someone else can help you out =)

**Comment by xiesi88** [comment] 2018-06-14 06:42
I have solved the problem and the installation is successful. If necessary, I can assist you in the Chinese translation.

**Comment by semontesdeoca** [comment] 2018-06-14 06:48
Nice, how did you solve it?

**Comment by xiesi88** [comment] 2018-06-14 06:54
I follow the solution 2 you provided.
Insert the system paths manually to the Maya environment.

**Comment by semontesdeoca** [comment] 2018-06-14 06:56
Alright, if anyone is reading this and has a Chinese version of Maya, it would be nice to get an automated fix for this in the code =)

**Comment by semontesdeoca** [comment] 2018-06-16 01:55
indeed, this seems likely to be the cause, can you try running this python snippet and share with me the print result?

```
import os
import coopLib as lib
def mayaVersion():
    """
    Returns the current Maya version (E.g. 2017.0, 2018.0, 2019.0, etc)
    """
    p = lib.Path(cmds.internalVar(usd=True)).parent()
    parent = lib.Path(p.path).parent()
    if os.path.basename(parent.path) == "maya":
        return float(os.path.basename(p.path))
    else:
        # foreign language versions
        return float(os.path.basename(parent.path))

print mayaVersion()
```

**Comment by kanzwataru** [comment] 2018-06-16 02:05
Whoops, already submitted a pull request for a similar thing. Let me just check yours quickly (looks a bit cleaner than mine)

**Comment by kanzwataru** [comment] 2018-06-16 02:08
Alright, that works too. Returns "2017.0". Although I wonder if it wouldn't be more robust to simply use:

`cmds.about(version=True)`

**Comment by semontesdeoca** [comment] 2018-06-16 02:13
I used to have it like that, but it didn't work once Maya introduced version 2016.5 and the command just returned 2016.
Thanks for the pull request, I'll edit it and merge it later today

**Comment by semontesdeoca** [comment] 2018-06-17 01:17
The new release is [is out](https://github.com/semontesdeoca/MNPR/releases).
Thank you guys for bringing this up!

**Closed by semontesdeoca** 2018-06-17 01:17 UTC
Labels: help wanted
